### ISSUE TITLE
pixiv icon

### ISSUE THREAD

**Issue by joshuah345** [Delta-Icons/iOS#2]
the android version has a pixiv icon, but it seems to be missing here.....

**Comment by leifniem** [comment]
That sadly is because nobody has been able to get the time to port more Android icons to iOS. If you want you can help out :)

**Comment by leifniem** [comment]
Finally closing this since i finally had time to whip up the migration tool which will fix this issue whenever someone has the patience to dig through all 4k android icons with it.
